### ISSUE TITLE
[Feature] Coerce DB2 type to equivalent JSON type

### ISSUE THREAD

**Issue by 2upmedia** [IBM/nodejs-idb-pconnector#51]
Since `fetch()` doesn't coerce the values in the result set it just returns string values, I worked on a subroutine that would do that. Not sure how you guys would want to implement this, if you'd like to. Here's the essence of the code:

```js
const {
  SQL_CHAR,
  SQL_NUMERIC,
  SQL_DECIMAL,
  SQL_INTEGER,
  SQL_SMALLINT,
  SQL_FLOAT,
  SQL_REAL,
  SQL_DOUBLE,
  SQL_DATETIME,
  SQL_VARCHAR,
  SQL_BLOB,
  SQL_CLOB,
  SQL_DBCLOB,
  SQL_DATALINK,
  SQL_WCHAR,
  SQL_WVARCHAR,
  SQL_BIGINT,
  SQL_BLOB_LOCATOR,
  SQL_CLOB_LOCATOR,
  SQL_DBCLOB_LOCATOR,
  SQL_UTF8_CHAR,
  SQL_WLONGVARCHAR,
  SQL_LONGVARCHAR,
  SQL_GRAPHIC,
  SQL_VARGRAPHIC,
  SQL_LONGVARGRAPHIC,
  SQL_BINARY,
  SQL_VARBINARY,
  SQL_LONGVARBINARY,
  SQL_DATE,
  SQL_TYPE_DATE,
  SQL_TIME,
  SQL_TYPE_TIME,
  SQL_TIMESTAMP,
  SQL_TYPE_TIMESTAMP,
  SQL_DECFLOAT,
  SQL_XML
} = require("idb-connector/lib/db2a");

/**
 *
 * @param {string} value
 * @return {number}
 */
function toNumber (value) {
  return Number(value);
}

/**
 *
 * @param {string} value
 * @return {string}
 */
function toString (value) {
  return String(value);
}

/**
 * matches DB2 Type to equivalent JSON type and returns a function that'll coerce the value
 *
 * @param {number} typeConstant a DB2 CLI constant
 * @return {(function(string): string)|(function(string): number)}
 */
function coerceDb2Type (typeConstant) {
  switch (typeConstant) {
    case SQL_CHAR:
    case SQL_VARCHAR:
    case SQL_LONGVARCHAR:
    case SQL_WCHAR:
    case SQL_WVARCHAR:
    case SQL_WLONGVARCHAR:
    case SQL_VARGRAPHIC:
    case SQL_LONGVARGRAPHIC:
    case SQL_VARBINARY:
    case SQL_LONGVARBINARY:
    case SQL_UTF8_CHAR:
    case SQL_XML:
      return toString;

    case SQL_NUMERIC:
    case SQL_DECIMAL:
    case SQL_INTEGER:
    case SQL_SMALLINT:
    case SQL_FLOAT:
    case SQL_REAL:
    case SQL_DOUBLE:
    case SQL_DECFLOAT:
      return toNumber;

    default:
      return toString;
  }
}

/**
 * Builds a map of with the key as the field name and value as a callback that will coerce the value into the equivalent JSON data type
 *
 * @param {Statement} statement
 * @return {Promise<Object<string, (function(string): string)|(function(string): number)>>}
 */
async function getFieldTypeMap(statement) {
  let map =  {};
  let numFields;

  try {
    numFields = await statement.numFields();
  } catch(e) {
    return map;
  }

  for (let i = 0; i < numFields; i++) {
    map[await statement.fieldName(i)] = coerceDb2Type(await statement.fieldType(i));
  }

  return map;
}

module.exports = {coerceDb2Type, getFieldTypeMap};
```

```js
let fieldTypeMap = await getFieldTypeMap(statement);
let row = await statement.fetch();

for (let fieldName in row) {
  row[fieldName] = fieldTypeMap[fieldName](row[fieldName]); // coerce value
}
```

**Comment by 2upmedia** [comment]
I don't mind doing a PR based on your suggestions.

**Comment by markdirish** [comment]
[So looking at the `fetchColData` function](https://github.com/IBM/nodejs-idb-connector/blob/04db5d4ddea301137db93b6a562a762283edeada/src/db2ia/dbstmt.cc#L2066) in `idb-connector` (the package that actually does the heavy lifting here), it looks like it should coerce `SQL_SMALLINT`, `SQL_INTEGER`, `SQL_DECIMAL`, and `SQL_NUMERIC` to be JavaScript numbers. Does it not coerce those for you, or are you trying to get different types back?

There are several issues here:
1. SQL_NUMERIC and SQL_DECIMAL can be larger than a JavaScript number can store, so in those cases they _should_ be returned as Strings, and then if stored in JSON as `Numbers` (or rather numbers), should be coerced. The problem is, the way you do it, by calling JavaScript's `Number()` function, they can potentially lose data if too big or too small. The better solution is to just enter it into JSON as a string, and then remove the quotes around it. Of course, if JavaScript is going to process that JSON string, you won't be able to just plop that value back into a Number variable, since again it might not be big enough for the data. Hmm...

2. We really need to support more data types. Off the top of my head, I can think of BIGINT (can fit in JavaScript's new BigInt class), REAL and DOUBLE (can fit in Number I believe), DECFLOAT (not sure the max size, will have to look into it).

3. I don't think the whole numFields / fetch / fetchAll workflow is that great, but that's more my beef with the connector than with your issue. There are a lot of `awaits` in your code that will slow down the execution of this function (but not of Node.js, just will increase the time to process _this_ function), but its all data that could have been returned when the query was ran.

4. If you want to implement it I would be fine with it, we just have to figure where it will go and what it will be called. Instead of `coerceDb2Type`, something like `jsonifyData`? I don't know, will have to brainstorm on it.

Thanks for working to make the connector better!

**Comment by 2upmedia** [comment]
You’re welcome!

What I noticed is that fetch() does not automatically coerce values. I’m not sure if that was by design, but that essentially what made me come up with these routines.

**Comment by abmusse** [comment]
@2upmedia 

Currently there is a way to return numeric data as a JS `Number`by using [dbstmt.asNumber](https://github.com/IBM/nodejs-idb-connector/tree/master/docs#dbstmtasnumberflag).

Please see this [issue](https://github.com/IBM/nodejs-idb-connector/issues/64).

We may just need to add a wrapper for  [dbstmt.asNumber](https://github.com/IBM/nodejs-idb-connector/tree/master/docs#dbstmtasnumberflag) in [statement.js](https://github.com/IBM/nodejs-idb-pconnector/blob/master/lib/statement.js)

**Comment by kadler** [comment]
Does #55 solve this?

**Comment by 2upmedia** [comment]
So far it doesn’t seem so. We’re using `prepare()` and `execute()` and the patch doesn’t seem to take effect. I’ve noted that in the issue.

**Comment by abmusse** [comment]
#55 adds a wrapper for [dbstmt.asNumber()](https://github.com/IBM/nodejs-idb-connector/tree/master/docs#dbstmtasnumberflag)

When enabled this will return `SMALLINT, INTEGER, DECIMAL, NUMERIC` sql types as JavaScript Number rather than the default String.

See https://github.com/IBM/nodejs-idb-connector/blob/master/src/db2ia/dbstmt.cc#L2260

I think adding conversions for the other types listed here:

```
SQL_FLOAT:
SQL_REAL:
SQL_DOUBLE:
SQL_DECFLOAT:
```

Would be better off implmented within [idb-connector](https://github.com/IBM/nodejs-idb-connector)

The following types will be returned as a JavaScript `Buffer` object

``` 
 SQL_VARBINARY:
 SQL_BINARY:
 SQL_BLOB:
```

All other types are already returned as JavaScript Strings.
